"""Invetory2

Revision ID: 452bb1698445
Revises: 806886a5b616
Create Date: 2020-03-21 13:33:27.622455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452bb1698445'
down_revision = '806886a5b616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('inventory', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('inventory', sa.Column('link', sa.String(length=256), nullable=True))
    op.add_column('inventory', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('inventory', sa.Column('price', sa.String(length=64), nullable=True))
    op.add_column('inventory', sa.Column('quantity', sa.String(length=128), nullable=True))
    op.add_column('inventory', sa.Column('size', sa.String(length=64), nullable=True))
    op.add_column('inventory', sa.Column('store', sa.String(length=128), nullable=True))
    op.drop_column('inventory', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('desc', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('inventory', 'store')
    op.drop_column('inventory', 'size')
    op.drop_column('inventory', 'quantity')
    op.drop_column('inventory', 'price')
    op.drop_column('inventory', 'phone')
    op.drop_column('inventory', 'link')
    op.drop_column('inventory', 'description')
    op.drop_column('inventory', 'address')
    # ### end Alembic commands ###
