"""empty message

Revision ID: 58c75b6454ea
Revises: 452bb1698445
Create Date: 2020-03-21 13:38:12.141916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c75b6454ea'
down_revision = '452bb1698445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_brand', table_name='inventory')
    op.drop_index('ix_inventory_sku', table_name='inventory')
    op.drop_index('ix_inventory_wtype', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=64), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=256), nullable=True),
    sa.Column('wtype', sa.VARCHAR(length=128), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=256), nullable=True),
    sa.Column('address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('link', sa.VARCHAR(length=256), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('price', sa.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=128), nullable=True),
    sa.Column('size', sa.VARCHAR(length=64), nullable=True),
    sa.Column('store', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_wtype', 'inventory', ['wtype'], unique=False)
    op.create_index('ix_inventory_sku', 'inventory', ['sku'], unique=False)
    op.create_index('ix_inventory_brand', 'inventory', ['brand'], unique=False)
    # ### end Alembic commands ###
