"""empty message

Revision ID: 8730e5972ff2
Revises: 327dc072b219
Create Date: 2020-03-28 11:51:18.129908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8730e5972ff2'
down_revision = '327dc072b219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datadatetime', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('wtype', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('store', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_history_address'), 'data_history', ['address'], unique=False)
    op.create_index(op.f('ix_data_history_datadatetime'), 'data_history', ['datadatetime'], unique=False)
    op.create_index(op.f('ix_data_history_sku'), 'data_history', ['sku'], unique=False)
    op.create_index(op.f('ix_data_history_store'), 'data_history', ['store'], unique=False)
    op.create_index(op.f('ix_data_history_wtype'), 'data_history', ['wtype'], unique=False)
    op.add_column('inventory', sa.Column('insertTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inventory_insertTime'), 'inventory', ['insertTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_insertTime'), table_name='inventory')
    op.drop_column('inventory', 'insertTime')
    op.drop_index(op.f('ix_data_history_wtype'), table_name='data_history')
    op.drop_index(op.f('ix_data_history_store'), table_name='data_history')
    op.drop_index(op.f('ix_data_history_sku'), table_name='data_history')
    op.drop_index(op.f('ix_data_history_datadatetime'), table_name='data_history')
    op.drop_index(op.f('ix_data_history_address'), table_name='data_history')
    op.drop_table('data_history')
    # ### end Alembic commands ###
