"""empty message

Revision ID: 9054109a7378
Revises: 58c75b6454ea
Create Date: 2020-03-21 13:38:35.127483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9054109a7378'
down_revision = '58c75b6454ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('wtype', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('store', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_brand'), 'inventory', ['brand'], unique=False)
    op.create_index(op.f('ix_inventory_sku'), 'inventory', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_wtype'), 'inventory', ['wtype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_wtype'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_sku'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_brand'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
