"""added completion time

Revision ID: e80800b8e893
Revises: 8730e5972ff2
Create Date: 2020-03-28 12:01:38.469501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80800b8e893'
down_revision = '8730e5972ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('last_update', sa.Column('completionTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_last_update_completionTime'), 'last_update', ['completionTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_last_update_completionTime'), table_name='last_update')
    op.drop_column('last_update', 'completionTime')
    # ### end Alembic commands ###
